// <auto-generated />
using BlackjackAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlackjackAPI.Migrations
{
    [DbContext(typeof(BlackjackAPIContext))]
    [Migration("20210301224652_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlackjackAPI.Models.Dealer", b =>
                {
                    b.Property<int>("DealerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("PlayStyle");

                    b.HasKey("DealerId");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            DealerId = 1,
                            Description = "Just a drifter, rolling wherever the wind takes him",
                            Name = "Tumbleweed Terrence",
                            PlayStyle = 4
                        },
                        new
                        {
                            DealerId = 2,
                            Description = "A ruthless rapscallion, chive-talker, onion hip-hop enthusiast",
                            Name = "Randall the Ruthless",
                            PlayStyle = 3
                        },
                        new
                        {
                            DealerId = 3,
                            Description = "A poker hand as deadly as her six-shooter",
                            Name = "Kissin' Kate Barlow",
                            PlayStyle = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
